package cg;

import java.util.Vector;

//        	   acct_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0) PRIMARY KEY,
//        	   name varchar(20) NOT NULL,
//        	   acct_type_id INT NOT NULL,
//        	   investor_id INT NOT NULL,
//        	   broker_id INT NOT NULL,
//        	   FOREIGN KEY (acct_type_id) REFERENCES acct_type(acct_type_id),
//        	   FOREIGN KEY (investor_id) REFERENCES investor(investor_id),
//        	   FOREIGN KEY (broker_id) REFERENCES broker(broker_id));

public class AccountInfo {
	public int    acct_id;
	public String name;
	public int    acct_type_id;
	public int    investor_id;
	public int    broker_id;
	
	/**
	 * Get the vector of names corresponding to a vector of account infos.
	 * @param aInfos
	 * @return A vector of account names.
	 */
	public static Vector<String> getNames(Vector<AccountInfo> aInfos)
	{
		Vector<String> tNames = new Vector<String>();

		for (AccountInfo tInfo: aInfos)
		{
			tNames.add(tInfo.name);
		}
		return tNames;
	}
	
	/*
	 * Get the account id corresponding to an account name.
	 */
	public static int getAccountId(Vector<AccountInfo> aInfos,String aName)
	{
		for (AccountInfo tInfo: aInfos)
		{
			if (tInfo.name.equals(aName))
			{
				return tInfo.acct_id;
			}
		}
		return -1;
	}

	public AccountInfo() {
	}
	
	public String toString() {
		  return
		      "id = " + acct_id + ";"
			+ "name = " + name + ";"
			+ "acct_type_id = " + acct_type_id + ";"
			+ "investor_id = " + investor_id + ";"
			+ "broker_id = " + broker_id + ";"
			+ "\n";
	}
}
